### PR TITLE
Added .tekton folder pipeline tasks workspace yaml files

### PR DESCRIPTION
**Pull request by bairixie**
added.tekton folder with pipeline , tasks ,  workspace  and built pipeline in the openshift 
Screenshot 2024-04-26 at 3 49 42 PM

Screenshot 2024-04-26 at 3 48 35 PM
 
Pipeline successfully run and pass the tasks

### CODE REVIEW

**Comment by nedjulius** [comment]
did you also create an openshift user and deploy it or is it just files for `tekton`?

**Comment by bairixie** [comment]
> did you also create an openshift user and deploy it or is it just files for `tekton`?

I created it on the openshift and copied the yaml file from that and delete the metadata, but I want to hold on to it for now since the professor sent an email saying he is going to talk about this next class

**Comment by nedjulius** [comment]
> > did you also create an openshift user and deploy it or is it just files for `tekton`?
> 
> I created it on the openshift and copied the yaml file from that and delete the metadata, but I want to hold on to it for now since the professor sent an email saying he is going to talk about this next class

makes sense. maybe we should merge this after the lecture so that we can set everything up in one go? what do you think?

**Comment by bairixie** [comment]
> > > did you also create an openshift user and deploy it or is it just files for `tekton`?
> > 
> > 
> > I created it on the openshift and copied the yaml file from that and delete the metadata, but I want to hold on to it for now since the professor sent an email saying he is going to talk about this next class
> 
> makes sense. maybe we should merge this after the lecture so that we can set everything up in one go? what do you think?

ok, no problem

**Comment by bairixie** [comment]
> > > did you also create an openshift user and deploy it or is it just files for `tekton`?
> > 
> > 
> > I created it on the openshift and copied the yaml file from that and delete the metadata, but I want to hold on to it for now since the professor sent an email saying he is going to talk about this next class
> 
> makes sense. maybe we should merge this after the lecture so that we can set everything up in one go? what do you think?

Do I need to delete the pipeline.yaml? I just saw professor's message in the homework channel

"========================
Building the OpenShift Pipeline
========================
To get started building your pipeline you can copy the .tekton/events/ folder, and the .tekton/tasks.yaml file and .tekton/workspace.yaml file from lab-openshift into your project repo. Then I would like each person on the team to add one task to the pipeline using the OpenShift Pipeline Builder editor.
Please do not apply the pipeline.yaml from lab-openshift otherwise there will be nothing for anyone to do."

**Comment by bairixie** [comment]
> added .tekton folder with pipeline , tasks , workspace in order to get started building our pipeline

**Comment by nedjulius** [comment]
does the deployment work now?

could you post the link?

**Review by nedjulius — APPROVED** [review]
looks good to me

**Pull request merged**
